BASE_DIR = "D:/models/UncertaintySlumDetection"
BATCH_SIZE = 32
CLASSES = 3
EARLY_STOPPING = 50
IMAGESIZE = 128
INITIAL_LEARNING_RATE = 1e-4
LIMIT_AOI = True
LOOCV_CITY = ["mumbai", "lagos", "nairobi"]
LSP = 25
MC_ITERATION = 50
MODEL = "ResNet50Custom"
OPTIMIZER = "adamw"
OVERLAP = 2
SAVE_PREDICTIONS = True
SEED = 42
SHOTS_PER_CLASS = [100, 200]
UNEVEN_IMAGE_TILES = "padding"
VAL_SHOTS_PER_CLASS = 200
VERBOSE = 2
WEIGHTED_LOSS = True
WARM_UP_EPOCHS = 5
WARM_UP_LEARNING_RATE = 1e-6

BASE_MODELPATH = BASE_DIR + "/models/base_models"
FINE_MODELPATH = BASE_DIR + "/models/finetune_models"
TRAINVALTEST_DATASET_DIR = BASE_DIR + "/data/datasets/" + str(IMAGESIZE) + "px"
IMAGE_STATS_PATH = TRAINVALTEST_DATASET_DIR + "_image_stats.csv"
RGB_PATH = BASE_DIR + "/data/{city}_3m.tif"
GT_PATH = BASE_DIR + "/data/{city}_slum_reference.tif"